import { type NextPage } from "next";
import Head from "next/head";
import Calendar from "../components/Calendar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Booking</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>
          <Calendar />
        </div>
      </main>
    </>
  );
};

export default Home;
