import { type NextPage } from "next";
import Head from "next/head";
import Calendar from "../components/Calendar";
import { formatISO } from "date-fns";
import { prisma } from "src/server/db";
import { Day } from "@prisma/client";

type HomeProps = {
  days: Day[];
  closedDays: string[]; // ISO strings
};

const Home: NextPage<HomeProps> = ({ days, closedDays }) => {
  return (
    <>
      <Head>
        <title>Booking</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Calendar days={days} closedDays={closedDays} />
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const days = await prisma.day.findMany();
  const closedDays = (await prisma.closedDay.findMany())?.map((day) =>
    formatISO(day.date)
  );
  return { props: { days, closedDays } };
}

export default Home;
